version: '3'

services:
  db:
    image: postgres:15.1
    container_name: postgres-database
    volumes:
      # creando un volumen en el mismo directorio
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123456

  pdAdmin:
    depends_on:
      - db
    image: dpage/pgadmin4:6.17
    ports:
      - 8080:80
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_PASSWORD=123456
      - PGADMIN_DEFAULT_EMAIL=test@test.com
